
// User actions
export const CREATE='CREATE';
export const UPDATE='UPDATE';
export const DELETE='DELETE';
export const FETCH_ALL='FETCH_ALL';
//services actions
export const FETCH_ALL_SERVICES='FETCH_ALL_SERVICES';
export const CREATE_SERVICE='CREATE_SERVICE';
export const DELETE_SERVICE='DELETE_SERVICE';
export const UPDATE_SERVICE='UPDATE_SERVICE';
export const SEARCH_SERVICE='SEARCH_SERVICE';
//Authentification 
export const LOGOUT='LOGOUT';
export const AUTH='AUTH';
//Request Data actions
export const FETCH_ALL_REQUEST_DATA='FETCH_ALL_REQUEST_DATA';
export const CREATE_REQUEST_DATA='CREATE_REQUEST_DATA';
export const DELETE_REQUEST_DATA='DELETE_REQUEST_DATA';
export const UPDATE_REQUEST_DATA='UPDATE_REQUEST_DATA';
//Messages 
export const ERROR='ERROR';
export const DELETEMESSAGE='DELETEMESSAGE';
export const SUCCESS="SUCCESS";
//categories 
export const FETCH_ALL_CATEGORIES='FETCH_ALL_CATEGORIES';

// Request actions
export const CREATE_REQUEST='CREATE_REQUEST';
export const UPDATE_REQUEST='UPDATE_REQUEST';
export const DELETE_REQUEST='DELETE_REQUEST';
export const FETCH_ALL_REQUESTS='FETCH_ALL_REQUESTS';

// Contact actions
export const CREATE_CONTACT='CREATE_CONTACT';

// Reviews actions
export const CREATE_REVIEW='CREATE_REVIEW';
export const FETCH_ALL_REVIEWS="FETCH_ALL_REVIEWS";

// Service Reviews actions
export const CREATE_SERVICEREVIEW='CREATE_SERVICEREVIEW';
export const FETCH_ALL_SERVICEREVIEWS="FETCH_ALL_SERVICEREVIEWS";
export const DELETE_SERVICEREVIEW="DELETE_SERVICEREVIEW";
// messages actions
export const CREATE_MESSAGE='CREATE_MESSAGE';
export const UPDATE_MESSAGE='UPDATE_MESSAGE';
export const DELETE_MESSAGE='DELETE_MESSAGE';
export const FETCH_ALL_MESSAGES='FETCH_ALL_MESSAGES';
export const FETCH_ALL_MESSAGES_BY_SENDER='FETCH_ALL_MESSAGES_BY_SENDER';
export const FETCH_ALL_MESSAGES_BY_RECEIVER='FETCH_ALL_MESSAGES_BY_RECEIVER';
export const COUNT_ALL_RECEIVED_MESSAGES = 'COUNT_ALL_RECEIVED_MESSAGES'
